In [1]:
import numpy as np
from PIL import Image

# Tensors

In the first notebook ([vector.ipynb](https://github.com/ADGEfficiency/teaching-monolith/blob/master/numpy/1.vector.ipynb)) we dealt with vectors (one dimensional).  In the second notebook ([matrix.ipynb](https://github.com/ADGEfficiency/teaching-monolith/blob/master/numpy/2.matrix.ipynb)) we looked at arrays with two dimensions.

Now we deal with **Tensors** - arrays that can have many dimensions.

- n-dimensional arrays
- 3 = volume
- uppercase, bold $\textbf{A}_{i,j,k}$

## Working in three dimensions

Extension of two dimensions
- everything we saw in the previous notebook holds

Images
- height
- width
- channels (colors)

Sequential models
- (batch_size, num_timesteps, *features)

In [2]:
#  three rows, three columns, three channels
image = np.random.rand(3, 3, 3)

image.shape

(3, 3, 3)

## Practical

Create an array filled from a normal distribution, with the shape
- 100 samples
- 64 timesteps
- 32 height
- 16 width
- 3 channels

In [3]:
np.random.rand()

0.31007612801204987

## Practical

Aggregate by standard deviation `np.std` 
- over the width
- over the height
- over the channels
- over all data

## PNG to Numpy array

In [4]:
# Reading in and displaying the image
img = Image.open('data/abbyroad.png')
img.show()

To see how this picture looks like in RGB code, we apply the following function:

In [5]:
array = np.array(img)
print(array)

[[[ 15  13  16]
  [ 15  13  16]
  [ 15  13  16]
  ...
  [ 20  20  18]
  [ 17  17  15]
  [ 16  16  14]]

 [[ 16  14  17]
  [ 16  14  17]
  [ 16  14  17]
  ...
  [ 21  21  19]
  [ 20  20  18]
  [ 20  20  18]]

 [[ 17  15  18]
  [ 17  15  18]
  [ 16  14  17]
  ...
  [ 21  21  19]
  [ 21  23  20]
  [ 22  24  21]]

 ...

 [[202 194 171]
  [199 191 168]
  [196 188 165]
  ...
  [205 195 159]
  [209 199 163]
  [213 203 167]]

 [[201 193 170]
  [197 189 166]
  [195 187 164]
  ...
  [206 198 161]
  [208 200 163]
  [213 205 168]]

 [[200 192 169]
  [196 188 165]
  [194 186 163]
  ...
  [209 201 164]
  [210 202 165]
  [214 206 169]]]


## Practical
Now create the negative version and grayscale version of that picture and save it in the data folder

In [6]:
# Inverse Color


In [7]:
# Grayscale Picture


## Answers
You are encourage to give it a try before you look at the solution

In [8]:
from Answers import inverse_color, grayscale
inverse_color(array)
grayscale(array)

## Practical - convolution

Implement the convolution operation - we will do this together as a class! The idea looks like this 
<img src="assets/conv.png" alt="" width="300"/>